import { readFile } from "node:fs/promises";
import { dirname, join } from "node:path";
import type { DiscoveredPluginDeclaration } from "@oiap/core";
import type * as TypeScript from "typescript";

type TypeScriptModule = typeof TypeScript;

interface HookRuntimeManifest {
	hooks?: Record<string, HookRuntimeHook>;
}

interface HookRuntimeHook {
	id: string;
	exportName?: string;
	handler?: { kind?: string };
}

interface HookBundleExport {
	id: string;
	exportName: string;
}

interface TopLevelBinding {
	statement: TypeScript.Statement;
	collectDependencies: boolean;
}

let typescriptModulePromise: Promise<TypeScriptModule> | undefined;

export async function bundleInstalledHookRuntime(options: {
	pluginFilePath: string;
	declaration: DiscoveredPluginDeclaration;
	outDir: string;
}): Promise<string[]> {
	const runtimeDirectory = join(options.outDir, ".oiap", "runtime");
	const manifestPath = join(runtimeDirectory, "manifest.json");
	const hooksPath = join(runtimeDirectory, "hooks.mjs");
	const manifest = await readHookRuntimeManifest(manifestPath);
	const runtimeHooks = Object.values(manifest?.hooks ?? {}).filter(
		(hook) => hook.exportName && hook.handler?.kind === "function",
	);

	if (runtimeHooks.length === 0) {
		return [];
	}

	const typescript = await loadTypescript();
	const source = await readFile(options.pluginFilePath, "utf8");
	const sourceFile = typescript.createSourceFile(
		options.pluginFilePath,
		source,
		typescript.ScriptTarget.Latest,
		true,
		scriptKindForPath(typescript, options.pluginFilePath),
	);
	const pluginObject = findPluginObjectLiteral(
		typescript,
		sourceFile,
		options.declaration,
	);

	if (!pluginObject) {
		return [];
	}

	const hooksExpression = pluginHooksExpression(
		typescript,
		sourceFile,
		pluginObject,
	);

	if (!hooksExpression) {
		throw new Error(
			`Could not locate a hooks expression in ${options.declaration.relativePath}; generated hook runtimes must be bundleable from source.`,
		);
	}

	await bundleHookEntry({
		entrySource: renderHookBundleEntry(
			typescript,
			sourceFile,
			hooksExpression,
			runtimeHooks.map((hook) => ({
				id: hook.id,
				exportName: hook.exportName as string,
			})),
		),
		hooksPath,
		pluginFilePath: options.pluginFilePath,
	});

	return [hooksPath];
}

async function readHookRuntimeManifest(
	manifestPath: string,
): Promise<HookRuntimeManifest | undefined> {
	try {
		return JSON.parse(
			await readFile(manifestPath, "utf8"),
		) as HookRuntimeManifest;
	} catch (error) {
		if (isFileNotFoundError(error)) {
			return undefined;
		}

		throw error;
	}
}

function findPluginObjectLiteral(
	typescript: TypeScriptModule,
	sourceFile: TypeScript.SourceFile,
	declaration: DiscoveredPluginDeclaration,
): TypeScript.ObjectLiteralExpression | undefined {
	let pluginObject: TypeScript.ObjectLiteralExpression | undefined;

	function visit(node: TypeScript.Node): void {
		if (pluginObject) {
			return;
		}

		if (typescript.isCallExpression(node)) {
			const position = sourceFile.getLineAndCharacterOfPosition(
				node.getStart(sourceFile),
			);

			if (
				position.line + 1 === declaration.line &&
				position.character + 1 === declaration.column
			) {
				const firstArgument = node.arguments[0];
				const expression = firstArgument
					? unwrapExpression(typescript, firstArgument)
					: undefined;

				if (expression && typescript.isObjectLiteralExpression(expression)) {
					pluginObject = expression;
				}
			}
		}

		typescript.forEachChild(node, visit);
	}

	visit(sourceFile);
	return pluginObject;
}

function pluginHooksExpression(
	typescript: TypeScriptModule,
	_sourceFile: TypeScript.SourceFile,
	pluginObject: TypeScript.ObjectLiteralExpression,
): TypeScript.Expression | undefined {
	const hooksExpression = objectLiteralPropertyExpression(
		typescript,
		pluginObject,
		"hooks",
	);

	return hooksExpression
		? unwrapExpression(typescript, hooksExpression)
		: undefined;
}

function renderHookBundleEntry(
	typescript: TypeScriptModule,
	sourceFile: TypeScript.SourceFile,
	hooksExpression: TypeScript.Expression,
	bundleExports: HookBundleExport[],
): string {
	const statements = collectRequiredTopLevelStatements(
		typescript,
		sourceFile,
		hooksExpression,
	);
	const lines = [
		"// Generated by install-agent-plugin. Do not edit.",
		...statements.map((statement) => statement.getText(sourceFile)),
		"",
		`const __oiapHooks = ${hooksExpression.getText(sourceFile)};`,
		"",
		"function __oiapHookHandler(id) {",
		"\tconst hook = __oiapHooks.find((candidate) => candidate && candidate.id === id);",
		"",
		'\tif (!hook || typeof hook.handler !== "function") {',
		'\t\tthrow new Error("OIAP hook " + id + " does not define a function handler.");',
		"\t}",
		"",
		"\treturn hook.handler;",
		"}",
		...bundleExports.flatMap((bundle) => [
			"",
			`export const ${bundle.exportName} = __oiapHookHandler(${JSON.stringify(bundle.id)});`,
		]),
		"",
	];

	return lines.join("\n");
}

function collectRequiredTopLevelStatements(
	typescript: TypeScriptModule,
	sourceFile: TypeScript.SourceFile,
	hooksExpression: TypeScript.Expression,
): TypeScript.Statement[] {
	const bindings = collectTopLevelBindings(typescript, sourceFile);
	const includedStatements = new Set<TypeScript.Statement>();

	function includeIdentifier(identifier: string): void {
		const binding = bindings.get(identifier);

		if (!binding || includedStatements.has(binding.statement)) {
			return;
		}

		includedStatements.add(binding.statement);

		if (binding.collectDependencies) {
			for (const dependency of collectReferencedIdentifiers(
				typescript,
				binding.statement,
			)) {
				includeIdentifier(dependency);
			}
		}
	}

	for (const identifier of collectReferencedIdentifiers(
		typescript,
		hooksExpression,
	)) {
		includeIdentifier(identifier);
	}

	return sourceFile.statements.filter((statement) =>
		includedStatements.has(statement),
	);
}

function collectTopLevelBindings(
	typescript: TypeScriptModule,
	sourceFile: TypeScript.SourceFile,
): Map<string, TopLevelBinding> {
	const bindings = new Map<string, TopLevelBinding>();

	for (const statement of sourceFile.statements) {
		if (typescript.isImportDeclaration(statement)) {
			for (const name of importBindingNames(typescript, statement)) {
				bindings.set(name, { statement, collectDependencies: false });
			}

			continue;
		}

		if (typescript.isVariableStatement(statement)) {
			for (const declaration of statement.declarationList.declarations) {
				for (const name of bindingPatternNames(typescript, declaration.name)) {
					bindings.set(name, { statement, collectDependencies: true });
				}
			}

			continue;
		}

		if (
			(typescript.isFunctionDeclaration(statement) ||
				typescript.isClassDeclaration(statement) ||
				typescript.isEnumDeclaration(statement)) &&
			statement.name
		) {
			bindings.set(statement.name.text, {
				statement,
				collectDependencies: true,
			});
		}
	}

	return bindings;
}

function importBindingNames(
	typescript: TypeScriptModule,
	statement: TypeScript.ImportDeclaration,
): string[] {
	const importClause = statement.importClause;

	if (!importClause || importClause.isTypeOnly) {
		return [];
	}

	const names: string[] = [];

	if (importClause.name) {
		names.push(importClause.name.text);
	}

	const namedBindings = importClause.namedBindings;

	if (!namedBindings) {
		return names;
	}

	if (typescript.isNamespaceImport(namedBindings)) {
		names.push(namedBindings.name.text);
		return names;
	}

	for (const specifier of namedBindings.elements) {
		if (!specifier.isTypeOnly) {
			names.push(specifier.name.text);
		}
	}

	return names;
}

function bindingPatternNames(
	typescript: TypeScriptModule,
	name: TypeScript.BindingName,
): string[] {
	if (typescript.isIdentifier(name)) {
		return [name.text];
	}

	return name.elements.flatMap((element) => {
		if (typescript.isOmittedExpression(element)) {
			return [];
		}

		return bindingPatternNames(typescript, element.name);
	});
}

function collectReferencedIdentifiers(
	typescript: TypeScriptModule,
	node: TypeScript.Node,
): Set<string> {
	const identifiers = new Set<string>();

	function visit(current: TypeScript.Node): void {
		if (typescript.isPropertyAccessExpression(current)) {
			visit(current.expression);
			return;
		}

		if (typescript.isPropertyAssignment(current)) {
			visit(current.initializer);
			return;
		}

		if (typescript.isShorthandPropertyAssignment(current)) {
			identifiers.add(current.name.text);
			return;
		}

		if (
			typescript.isIdentifier(current) &&
			!isDeclarationName(typescript, current)
		) {
			identifiers.add(current.text);
		}

		typescript.forEachChild(current, visit);
	}

	visit(node);
	return identifiers;
}

function isDeclarationName(
	typescript: TypeScriptModule,
	identifier: TypeScript.Identifier,
): boolean {
	const parent = identifier.parent;

	return Boolean(
		(parent &&
			((isNamedDeclaration(parent) && parent.name === identifier) ||
				(typescript.isImportSpecifier(parent) && parent.name === identifier) ||
				(typescript.isBindingElement(parent) && parent.name === identifier))) ||
			(parent && typescript.isParameter(parent) && parent.name === identifier),
	);
}

function isNamedDeclaration(
	node: TypeScript.Node,
): node is TypeScript.NamedDeclaration {
	return "name" in node;
}

async function bundleHookEntry(options: {
	entrySource: string;
	hooksPath: string;
	pluginFilePath: string;
}): Promise<void> {
	const { build } = (await import("esbuild")) as typeof import("esbuild");

	await build({
		absWorkingDir: dirname(options.pluginFilePath),
		bundle: true,
		format: "esm",
		logLevel: "silent",
		outfile: options.hooksPath,
		platform: "node",
		stdin: {
			contents: options.entrySource,
			loader: "ts",
			resolveDir: dirname(options.pluginFilePath),
			sourcefile: "oiap-hook-runtime-entry.ts",
		},
		target: "node20",
		treeShaking: true,
	});
}

function objectLiteralProperty(
	typescript: TypeScriptModule,
	objectLiteral: TypeScript.ObjectLiteralExpression,
	name: string,
): TypeScript.ObjectLiteralElementLike | undefined {
	return objectLiteral.properties.find((property) => {
		const propertyName = property.name;

		return (
			propertyName &&
			((typescript.isIdentifier(propertyName) && propertyName.text === name) ||
				(typescript.isStringLiteral(propertyName) &&
					propertyName.text === name))
		);
	});
}

function objectLiteralPropertyExpression(
	typescript: TypeScriptModule,
	objectLiteral: TypeScript.ObjectLiteralExpression,
	name: string,
): TypeScript.Expression | undefined {
	const property = objectLiteralProperty(typescript, objectLiteral, name);

	if (!property) {
		return undefined;
	}

	if (typescript.isPropertyAssignment(property)) {
		return property.initializer;
	}

	if (
		name === property.name?.getText() &&
		typescript.isShorthandPropertyAssignment(property)
	) {
		return property.name;
	}

	return undefined;
}

function unwrapExpression(
	typescript: TypeScriptModule,
	expression: TypeScript.Expression,
): TypeScript.Expression {
	let current = expression;

	while (
		typescript.isParenthesizedExpression(current) ||
		typescript.isAsExpression(current) ||
		typescript.isSatisfiesExpression(current) ||
		typescript.isTypeAssertionExpression(current)
	) {
		current = current.expression;
	}

	return current;
}

function scriptKindForPath(
	typescript: TypeScriptModule,
	filePath: string,
): TypeScript.ScriptKind {
	if (filePath.endsWith(".tsx")) {
		return typescript.ScriptKind.TSX;
	}

	if (filePath.endsWith(".jsx")) {
		return typescript.ScriptKind.JSX;
	}

	if (filePath.endsWith(".js") || filePath.endsWith(".mjs")) {
		return typescript.ScriptKind.JS;
	}

	if (filePath.endsWith(".cjs")) {
		return typescript.ScriptKind.JS;
	}

	return typescript.ScriptKind.TS;
}

async function loadTypescript(): Promise<TypeScriptModule> {
	if (!typescriptModulePromise) {
		typescriptModulePromise = import("typescript");
	}

	return await typescriptModulePromise;
}

function isFileNotFoundError(error: unknown): boolean {
	if (!error || typeof error !== "object") {
		return false;
	}

	return "code" in error && (error as { code?: unknown }).code === "ENOENT";
}
